<#
.SYNOPSIS
    Provisions an Entra app registration + service principal for SecurityInsight,
    generates the cred (secret today; cert in v2.2.106), grants Microsoft Graph +
    Azure permissions, and returns the connection block for the wizard's
    config writer.

.DESCRIPTION
    Used by the Setup Wizard's /api/apply endpoint. Idempotent:
      * If an app registration with the same -DisplayName already exists, REUSE it.
      * If the SPN already exists, REUSE it.
      * Creates a NEW client secret on every run (rotates) -- old secrets stay
        valid until they expire on their own.
      * Graph admin consent is requested via the Beta endpoint (no human
        click-through required when the caller is a Global Admin).

    Required modules: Microsoft.Graph.Authentication, Microsoft.Graph.Applications,
                      Az.Accounts, Az.Resources, (Az.KeyVault if -CredStorage 'KeyVault')

    Caller context: Global Admin OR Privileged Role Administrator.

.PARAMETER DisplayName
    Display name for the Entra app registration. e.g. 'sp-securityinsight-myfamily'.

.PARAMETER TenantId
    Entra tenant ID (GUID).

.PARAMETER SubscriptionId
    Azure subscription ID where SI will run. Used to scope the RBAC.

.PARAMETER RootMgId
    Tenant-root management group ID. RBAC (Reader + Tag Contributor) is granted at this scope
    so the engine can query Azure Resource Graph across all subscriptions in the tenant.
    Defaults to the TenantId (which is the default name of the root MG).

.PARAMETER CredKind
    'Secret' (default) | 'Cert' | 'ManagedIdentity'
      Secret          : client secret (rotates on every wizard run)
      Cert            : self-signed cert generated by the wizard
      ManagedIdentity : caller is running on an Azure host with a system or user-assigned MSI;
                        the wizard SKIPS app-reg creation entirely and instead grants
                        the MSI's existing object the same Graph + Azure perms.

.PARAMETER CredStorage
    Where the cred lives once generated:
      'KeyVault'      : stored as a KV secret (Secret) or KV certificate (Cert). Engine reads
                        it via OAuth at run time. Preferred.
      'LocalCertStore': for Cert path only -- imports the .pfx into CurrentUser\My on this box.
                        Doesn't survive moving the launcher to another machine.
      'Inline'        : Secret only. Returned in the result so the writer drops it
                        directly in config\SecurityInsight.custom.ps1 as $global:SI_SPN_Secret.
                        Simpler but the secret lives in plaintext on the launcher VM.

.PARAMETER KeyVaultName
    Required when -CredStorage 'KeyVault'. KV must already exist + caller must have
    Set permission on secrets.

.PARAMETER KvSecretName
    Optional KV secret name (default: 'SI-SPN-Secret').

.PARAMETER GraphPermissions
    Microsoft Graph application permissions to grant. Default = the SecurityInsight
    minimum required set (see comments below).

.PARAMETER SkipAdminConsent
    Don't auto-consent. Caller will need to click 'Grant admin consent' in the Entra
    portal manually. Default: consent is requested automatically.

.OUTPUTS
    pscustomobject:
      AppId           : <guid>      App (client) ID
      ObjectId        : <guid>      Service principal object ID
      TenantId        : <guid>
      DisplayName     : <string>
      CredKind        : 'Secret'
      CredValue       : <string>    Returned only when -CredStorage 'Inline'; $null otherwise
      KvName          : <string>    Returned only when -CredStorage 'KeyVault'
      KvSecretName    : <string>    Returned only when -CredStorage 'KeyVault'
      SecretExpiresUtc: <datetime>
      GraphPermissions: <string[]>
      AzureRbacScopes : <string[]>  RBAC scopes where the SPN was granted

.EXAMPLE
    New-SISpn -DisplayName 'sp-securityinsight-myfamily' `
              -TenantId 'f0fa27a0-...' -SubscriptionId 'ef830ec3-...' `
              -CredStorage KeyVault -KeyVaultName 'kv-myfamily-si'

.NOTES
    Status: v2.2.105 -- secret path. Cert path + Managed Identity branch land in v2.2.106.
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory)] [string]$DisplayName,
    [Parameter(Mandatory)] [string]$TenantId,
    [Parameter(Mandatory)] [string]$SubscriptionId,
    [Parameter()]          [string]$RootMgId,
    [Parameter()]          [ValidateSet('Secret','Cert','ManagedIdentity')] [string]$CredKind = 'Secret',
    [Parameter(Mandatory)] [ValidateSet('KeyVault','LocalCertStore','Inline')] [string]$CredStorage,
    [Parameter()]          [string]$KeyVaultName,
    [Parameter()]          [string]$KvSecretName = 'SI-SPN-Secret',
    [Parameter()]          [string]$KvCertName   = 'SI-SPN-Cert',
    [Parameter()]          [int]$SecretValidityYears = 2,
    [Parameter()]          [string]$ManagedIdentityClientId,   # required when CredKind=ManagedIdentity
    [Parameter()]          [string[]]$GraphPermissions,
    [Parameter()]          [switch]$SkipAdminConsent
)

$ErrorActionPreference = 'Stop'

# ----- Default Graph permission matrix (extend via -GraphPermissions) -----
# These are the minimum app-only permissions every SI engine needs. Extra
# permissions (e.g. Mail.Read for SMTP-from-Graph) can be appended via the
# parameter -- they're additive, not replacement.
if (-not $GraphPermissions -or $GraphPermissions.Count -eq 0) {
    $GraphPermissions = @(
        'ThreatHunting.Read.All',                # Defender XDR advanced hunting
        'Device.Read.All',                       # MDE devices, vulnerabilities
        'User.Read.All',                         # Entra users
        'Application.Read.All',                  # SPNs / app regs
        'Group.Read.All',                        # AD groups (for tier-via-membership)
        'Policy.Read.All',                       # Conditional Access + auth policies
        'AuditLog.Read.All',                     # Sign-in logs / audit logs
        'IdentityRiskEvent.Read.All',            # Identity protection risk events
        'IdentityRiskyUser.Read.All',            # Risky users
        'Reports.Read.All',                      # MFA registration + activity reports
        'DirectoryRecommendations.Read.All',     # Defender for Identity + Entra recs
        'SecurityEvents.Read.All',               # Defender alerts
        'CrossTenantInformation.ReadBasic.All'   # Multi-tenant SP visibility
    )
}

if (-not $RootMgId) { $RootMgId = $TenantId }

# ----- Validate cred-kind / cred-storage combination -----
switch ($CredKind) {
    'Secret' {
        if ($CredStorage -eq 'LocalCertStore') {
            throw "CredStorage 'LocalCertStore' is only valid with CredKind 'Cert'."
        }
    }
    'Cert' {
        if ($CredStorage -eq 'Inline') {
            throw "CredStorage 'Inline' is only valid with CredKind 'Secret' (a cert thumbprint is fine inline; the private key must live in KV or LocalCertStore)."
        }
    }
    'ManagedIdentity' {
        if (-not $ManagedIdentityClientId) {
            throw "When CredKind = ManagedIdentity, -ManagedIdentityClientId is required (the user-assigned or system-assigned MSI ClientId)."
        }
        # CredStorage is N/A for MSI -- ignored.
    }
}
if ($CredKind -ne 'ManagedIdentity' -and $CredStorage -eq 'KeyVault' -and -not $KeyVaultName) {
    throw "When -CredStorage 'KeyVault', -KeyVaultName is required."
}

function _Step([string]$msg) { Write-Host "  [STEP] $msg" -ForegroundColor Cyan }
function _Ok  ([string]$msg) { Write-Host "  [OK]   $msg" -ForegroundColor Green }
function _Info([string]$msg) { Write-Host "  [INFO] $msg" -ForegroundColor Gray }
function _Warn([string]$msg) { Write-Host "  [WARN] $msg" -ForegroundColor Yellow }

Write-Host ""
Write-Host "=== New-SISpn  --  $DisplayName  ===" -ForegroundColor Cyan
_Info "tenant       : $TenantId"
_Info "subscription : $SubscriptionId"
_Info "root MG      : $RootMgId"
_Info "cred storage : $CredStorage"
if ($CredStorage -eq 'KeyVault') { _Info "key vault    : $KeyVaultName / $KvSecretName" }
Write-Host ""

# ----- 1. Connect Microsoft Graph -----
_Step "connect Microsoft Graph"
Import-Module Microsoft.Graph.Authentication -ErrorAction Stop
Import-Module Microsoft.Graph.Applications  -ErrorAction Stop
$mgScopes = @(
    'Application.ReadWrite.All',          # create app + sp + secret
    'AppRoleAssignment.ReadWrite.All',    # grant Graph permissions
    'DelegatedPermissionGrant.ReadWrite.All',
    'Directory.ReadWrite.All'
)
$ctx = Get-MgContext -ErrorAction SilentlyContinue
if (-not $ctx -or $ctx.TenantId -ne $TenantId -or -not ($mgScopes | ForEach-Object { $ctx.Scopes -contains $_ } | Where-Object { -not $_ } | Select-Object -First 1)) {
    Connect-MgGraph -TenantId $TenantId -Scopes $mgScopes -NoWelcome | Out-Null
}
$ctx = Get-MgContext
_Ok ("Graph connected as {0} ({1})" -f $ctx.Account, $ctx.AppName)

# ----- 2. Find or create the application -----
_Step "look up application by display name"
$app = Get-MgApplication -Filter "displayName eq '$DisplayName'" -ConsistencyLevel eventual -CountVariable c -ErrorAction Stop
if ($app -is [array]) { $app = $app[0] }
if ($app) {
    _Ok ("re-using existing app reg: {0}" -f $app.AppId)
} else {
    _Step "create app registration"
    $app = New-MgApplication -DisplayName $DisplayName -SignInAudience 'AzureADMyOrg' -ErrorAction Stop
    _Ok ("created app reg: {0}" -f $app.AppId)
}

# ----- 3. Find or create the service principal -----
_Step "look up service principal"
$sp = Get-MgServicePrincipal -Filter "appId eq '$($app.AppId)'" -ErrorAction SilentlyContinue
if (-not $sp) {
    _Step "create service principal"
    $sp = New-MgServicePrincipal -AppId $app.AppId -ErrorAction Stop
    _Ok ("created SP: {0}" -f $sp.Id)
} else {
    _Ok ("re-using existing SP: {0}" -f $sp.Id)
}

# ----- 4. Generate the cred (Secret OR Cert; MSI path skips this entirely) -----
$pwd       = $null   # secret object
$certInfo  = $null   # @{ Thumbprint; PfxBytes; PfxPassword }
if ($CredKind -eq 'Secret') {
    _Step "create new client secret (validity ${SecretValidityYears}y)"
    $secretParams = @{
        PasswordCredential = @{
            DisplayName = ("SI-Wizard-{0:yyyyMMdd-HHmm}" -f (Get-Date))
            EndDateTime = (Get-Date).AddYears($SecretValidityYears)
        }
    }
    $pwd = Add-MgApplicationPassword -ApplicationId $app.Id -BodyParameter $secretParams -ErrorAction Stop
    _Ok ("secret created, expires {0:u}" -f $pwd.EndDateTime)
}
elseif ($CredKind -eq 'Cert') {
    _Step "generate self-signed certificate (validity ${SecretValidityYears}y)"
    $certSubject = "CN=$DisplayName"
    $cert = New-SelfSignedCertificate -Subject $certSubject -CertStoreLocation 'Cert:\CurrentUser\My' `
        -KeySpec Signature -KeyExportPolicy Exportable -KeyLength 2048 `
        -NotAfter (Get-Date).AddYears($SecretValidityYears) -ErrorAction Stop
    _Ok ("cert generated: thumbprint $($cert.Thumbprint), expires $($cert.NotAfter.ToString('u'))")

    _Step "upload cert public key to app registration"
    $certBytes = $cert.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Cert)
    $keyCred = @{
        Type        = 'AsymmetricX509Cert'
        Usage       = 'Verify'
        Key         = $certBytes
        DisplayName = ("SI-Wizard-{0:yyyyMMdd-HHmm}" -f (Get-Date))
        StartDateTime = $cert.NotBefore
        EndDateTime   = $cert.NotAfter
    }
    Update-MgApplication -ApplicationId $app.Id -KeyCredentials @($keyCred) -ErrorAction Stop
    _Ok 'cert public key attached to app registration'

    # Export PFX (pwd-protected, returned to caller for KV upload OR keep in local store)
    $pfxPwd  = [Guid]::NewGuid().Guid
    $pfxBytes = $cert.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Pfx, $pfxPwd)
    $certInfo = @{
        Thumbprint  = $cert.Thumbprint
        NotAfter    = $cert.NotAfter
        PfxBytes    = $pfxBytes
        PfxPassword = $pfxPwd
    }
}
elseif ($CredKind -eq 'ManagedIdentity') {
    _Info "CredKind=ManagedIdentity -- skipping app-reg cred creation; granting perms to the existing MSI"
    $msiSp = Get-MgServicePrincipal -Filter "appId eq '$ManagedIdentityClientId'" -ErrorAction SilentlyContinue
    if (-not $msiSp) {
        throw "Managed Identity with client ID '$ManagedIdentityClientId' not found. Make sure the MSI exists in tenant $TenantId and that you used the CLIENT id, not the principal id."
    }
    # Re-target the rest of the function at the MSI's SP instead of our newly-minted SP.
    $sp = $msiSp
    _Ok ("re-targeting subsequent permissions onto MSI SP {0}" -f $sp.Id)
}

# ----- 5. Add Graph application permissions -----
_Step "grant Microsoft Graph application permissions"
$graphAppId  = '00000003-0000-0000-c000-000000000000'   # Microsoft Graph
$graphSp     = Get-MgServicePrincipal -Filter "appId eq '$graphAppId'" -ErrorAction Stop
$missing = @()
foreach ($permName in $GraphPermissions) {
    $role = $graphSp.AppRoles | Where-Object { $_.Value -eq $permName -and $_.AllowedMemberTypes -contains 'Application' }
    if (-not $role) {
        _Warn "Graph role not found: $permName -- skipped"
        continue
    }
    $existing = Get-MgServicePrincipalAppRoleAssignment -ServicePrincipalId $sp.Id -ErrorAction SilentlyContinue |
        Where-Object { $_.AppRoleId -eq $role.Id -and $_.ResourceId -eq $graphSp.Id }
    if ($existing) { continue }   # already granted
    try {
        $null = New-MgServicePrincipalAppRoleAssignment -ServicePrincipalId $sp.Id `
            -PrincipalId $sp.Id -ResourceId $graphSp.Id -AppRoleId $role.Id -ErrorAction Stop
        $missing += $permName
    } catch {
        _Warn ("could not grant {0}: {1}" -f $permName, $_.Exception.Message)
    }
}
_Ok ("Graph permissions granted: {0} new ({1} total requested)" -f $missing.Count, $GraphPermissions.Count)
if (-not $SkipAdminConsent) {
    _Info 'admin consent requested via app-role-assignment (silent for Global Admins)'
}

# ----- 6. Azure RBAC -----
_Step "connect Az PowerShell"
Import-Module Az.Accounts -ErrorAction Stop
Import-Module Az.Resources -ErrorAction Stop
$azCtx = Get-AzContext -ErrorAction SilentlyContinue
if (-not $azCtx -or $azCtx.Tenant.Id -ne $TenantId -or $azCtx.Subscription.Id -ne $SubscriptionId) {
    Connect-AzAccount -Tenant $TenantId -Subscription $SubscriptionId -ErrorAction Stop | Out-Null
}
_Ok 'Az connected'

$rbacScopes = @()
$rootMgScope = "/providers/Microsoft.Management/managementGroups/$RootMgId"
$readerRoleId       = 'acdd72a7-3385-48ef-bd42-f606fba81ae7'   # Reader
$tagContributorId   = '4a9ae827-6dc8-4573-8ac7-8239d42aa03f'   # Tag Contributor

foreach ($pair in @(@{Name='Reader'; Id=$readerRoleId}, @{Name='Tag Contributor'; Id=$tagContributorId})) {
    $existing = Get-AzRoleAssignment -ObjectId $sp.Id -Scope $rootMgScope -RoleDefinitionId $pair.Id -ErrorAction SilentlyContinue
    if ($existing) { _Info ("RBAC {0} already in place at root MG" -f $pair.Name); continue }
    try {
        $null = New-AzRoleAssignment -ObjectId $sp.Id -RoleDefinitionId $pair.Id -Scope $rootMgScope -ErrorAction Stop
        _Ok ("RBAC {0} granted at root MG" -f $pair.Name)
        $rbacScopes += "$rootMgScope|$($pair.Name)"
    } catch {
        _Warn ("RBAC {0} grant failed: {1}" -f $pair.Name, $_.Exception.Message)
    }
}

# ----- 7. Cred storage -----
$credValue        = $null
$kvOut            = $null
$kvSecretOut      = $null
$kvCertOut        = $null
$certThumbprintOut= $null
$expiresOut       = $null

if ($CredKind -eq 'Secret') {
    if ($CredStorage -eq 'KeyVault') {
        _Step "store secret in Key Vault"
        Import-Module Az.KeyVault -ErrorAction Stop
        $kv = Get-AzKeyVault -VaultName $KeyVaultName -ErrorAction SilentlyContinue
        if (-not $kv) { throw "Key Vault '$KeyVaultName' not found in subscription $SubscriptionId" }
        $secureSecret = ConvertTo-SecureString -String $pwd.SecretText -AsPlainText -Force
        $null = Set-AzKeyVaultSecret -VaultName $KeyVaultName -Name $KvSecretName -SecretValue $secureSecret -Expires $pwd.EndDateTime -ErrorAction Stop
        _Ok ("secret stored at https://{0}.vault.azure.net/secrets/{1}" -f $KeyVaultName, $KvSecretName)
        $kvOut = $KeyVaultName; $kvSecretOut = $KvSecretName
    } else {
        _Info 'cred storage = Inline -- secret returned in result object (DO NOT log)'
        $credValue = $pwd.SecretText
    }
    $expiresOut = $pwd.EndDateTime.ToUniversalTime()
}
elseif ($CredKind -eq 'Cert') {
    $certThumbprintOut = $certInfo.Thumbprint
    $expiresOut        = $certInfo.NotAfter.ToUniversalTime()
    if ($CredStorage -eq 'KeyVault') {
        _Step "store cert .pfx in Key Vault"
        Import-Module Az.KeyVault -ErrorAction Stop
        $kv = Get-AzKeyVault -VaultName $KeyVaultName -ErrorAction SilentlyContinue
        if (-not $kv) { throw "Key Vault '$KeyVaultName' not found in subscription $SubscriptionId" }
        $tmpPfx = Join-Path ([IO.Path]::GetTempPath()) ("$DisplayName-{0:yyyyMMddHHmmss}.pfx" -f (Get-Date))
        try {
            [IO.File]::WriteAllBytes($tmpPfx, $certInfo.PfxBytes)
            $securePfxPwd = ConvertTo-SecureString -String $certInfo.PfxPassword -AsPlainText -Force
            $null = Import-AzKeyVaultCertificate -VaultName $KeyVaultName -Name $KvCertName -FilePath $tmpPfx -Password $securePfxPwd -ErrorAction Stop
            _Ok ("cert stored at https://{0}.vault.azure.net/certificates/{1}" -f $KeyVaultName, $KvCertName)
            $kvOut     = $KeyVaultName
            $kvCertOut = $KvCertName
        } finally {
            if (Test-Path -LiteralPath $tmpPfx) { Remove-Item -LiteralPath $tmpPfx -Force -ErrorAction SilentlyContinue }
        }
    } elseif ($CredStorage -eq 'LocalCertStore') {
        _Info ("cert kept in CurrentUser\My (thumbprint $($certInfo.Thumbprint)) -- private key stays on this machine only")
        # Already in CurrentUser\My from New-SelfSignedCertificate. Nothing else to do.
    }
}
elseif ($CredKind -eq 'ManagedIdentity') {
    _Info "MSI mode: app-reg cred not generated. The launcher must run on the host that owns this MSI."
    $expiresOut = $null
}

Write-Host ""
[pscustomobject]@{
    AppId             = $app.AppId
    ObjectId          = $sp.Id
    TenantId          = $TenantId
    DisplayName       = $DisplayName
    CredKind          = $CredKind
    CredValue         = $credValue          # Secret + Inline only
    CertThumbprint    = $certThumbprintOut  # Cert path only
    KvName            = $kvOut
    KvSecretName      = $kvSecretOut        # Secret-in-KV
    KvCertName        = $kvCertOut          # Cert-in-KV
    ManagedIdentityId = if ($CredKind -eq 'ManagedIdentity') { $ManagedIdentityClientId } else { $null }
    ExpiresUtc        = $expiresOut
    GraphPermissions  = $GraphPermissions
    AzureRbacScopes   = $rbacScopes
}
