<#
.SYNOPSIS
    Provisions an Entra app registration + service principal for SecurityInsight,
    generates the cred (secret today; cert in v2.2.106), grants Microsoft Graph +
    Azure permissions, and returns the connection block for the wizard's
    config writer.

.DESCRIPTION
    Used by the Setup Wizard's /api/apply endpoint. Idempotent:
      * If an app registration with the same -DisplayName already exists, REUSE it.
      * If the SPN already exists, REUSE it.
      * Creates a NEW client secret on every run (rotates) -- old secrets stay
        valid until they expire on their own.
      * Graph admin consent is requested via the Beta endpoint (no human
        click-through required when the caller is a Global Admin).

    Required modules: Microsoft.Graph.Authentication, Microsoft.Graph.Applications,
                      Az.Accounts, Az.Resources, (Az.KeyVault if -CredStorage 'KeyVault')

    Caller context: Global Admin OR Privileged Role Administrator.

.PARAMETER DisplayName
    Display name for the Entra app registration. e.g. 'sp-securityinsight-myfamily'.

.PARAMETER TenantId
    Entra tenant ID (GUID).

.PARAMETER SubscriptionId
    Azure subscription ID where SI will run. Used to scope the RBAC.

.PARAMETER RootMgId
    Tenant-root management group ID. RBAC (Reader by default; Tag Contributor only when -IncludeTagContributor is set) is granted at this scope
    so the engine can query Azure Resource Graph across all subscriptions in the tenant.
    Defaults to the TenantId (which is the default name of the root MG).

.PARAMETER CredKind
    'Secret' (default) | 'Cert' | 'ManagedIdentity'
      Secret          : client secret (rotates on every wizard run)
      Cert            : self-signed cert generated by the wizard
      ManagedIdentity : caller is running on an Azure host with a system or user-assigned MSI;
                        the wizard SKIPS app-reg creation entirely and instead grants
                        the MSI's existing object the same Graph + Azure perms.

.PARAMETER CredStorage
    Where the cred lives once generated:
      'KeyVault'      : stored as a KV secret (Secret) or KV certificate (Cert). Engine reads
                        it via OAuth at run time. Preferred.
      'LocalCertStore': for Cert path only -- imports the .pfx into CurrentUser\My on this box.
                        Doesn't survive moving the launcher to another machine.
      'Inline'        : Secret only. Returned in the result so the writer drops it
                        directly in config\SecurityInsight.custom.ps1 as $global:SI_SPN_Secret.
                        Simpler but the secret lives in plaintext on the launcher VM.

.PARAMETER KeyVaultName
    Required when -CredStorage 'KeyVault'. KV must already exist + caller must have
    Set permission on secrets.

.PARAMETER KvSecretName
    Optional KV secret name (default: 'SI-SPN-Secret').

.PARAMETER GraphPermissions
    Microsoft Graph application permissions to grant. Default = the SecurityInsight
    minimum required set (see comments below).

.PARAMETER SkipAdminConsent
    Don't auto-consent. Caller will need to click 'Grant admin consent' in the Entra
    portal manually. Default: consent is requested automatically.

.OUTPUTS
    pscustomobject:
      AppId           : <guid>      App (client) ID
      ObjectId        : <guid>      Service principal object ID
      TenantId        : <guid>
      DisplayName     : <string>
      CredKind        : 'Secret'
      CredValue       : <string>    Returned only when -CredStorage 'Inline'; $null otherwise
      KvName          : <string>    Returned only when -CredStorage 'KeyVault'
      KvSecretName    : <string>    Returned only when -CredStorage 'KeyVault'
      SecretExpiresUtc: <datetime>
      GraphPermissions: <string[]>
      AzureRbacScopes : <string[]>  RBAC scopes where the SPN was granted

.EXAMPLE
    New-SISpn -DisplayName 'sp-securityinsight-myfamily' `
              -TenantId 'f0fa27a0-...' -SubscriptionId 'ef830ec3-...' `
              -CredStorage KeyVault -KeyVaultName 'kv-myfamily-si'

.NOTES
    Status: v2.2.105 -- secret path. Cert path + Managed Identity branch land in v2.2.106.
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter()]          [string]$DisplayName,                                                                        # required UNLESS -UseExistingAppId
    [Parameter(Mandatory)] [string]$TenantId,
    [Parameter(Mandatory)] [string]$SubscriptionId,
    [Parameter()]          [string]$RootMgId,
    [Parameter()]          [ValidateSet('Secret','Cert','ManagedIdentity')] [string]$CredKind = 'Secret',
    [Parameter()]          [ValidateSet('KeyVault','LocalCertStore','Inline')] [string]$CredStorage,                    # required UNLESS -UseExistingAppId
    [Parameter()]          [string]$KeyVaultName,
    [Parameter()]          [string]$KvSecretName = 'SI-SPN-Secret',
    [Parameter()]          [string]$KvCertName   = 'SI-SPN-Cert',
    [Parameter()]          [int]$SecretValidityYears = 2,
    [Parameter()]          [string]$ManagedIdentityClientId,   # required when CredKind=ManagedIdentity
    [Parameter()]          [string[]]$GraphPermissions,
    [Parameter()]          [string[]]$ThreatProtectionPermissions,
    [Parameter()]          [string[]]$WindowsDefenderAtpPermissions,
    [Parameter()]          [switch]$SkipAdminConsent,
    [Parameter()]          [switch]$SkipTenantRbac,
    [Parameter()]          [switch]$IncludeTagContributor,  # opt-in: granted ONLY when asset-exclusion-tagging engine is in scope

    # ---- Use-existing-SPN mode (Setup-SecurityInsight-Unattended.ps1 Internal flavour) ----
    # When -UseExistingAppId is set, the cmdlet skips Create-app-registration AND
    # cred generation. Caller passes the v1 cert-based SPN's AppId; the cmdlet
    # looks up the SP by AppId, then runs the existing perms-grant + RBAC blocks
    # idempotently against the looked-up SP. The cert in the local store stays
    # the only credential material -- no secret is generated, nothing is written
    # to disk, nothing is added to Key Vault.
    [Parameter()]          [switch]$UseExistingAppId,
    [Parameter()]          [string]$ExistingAppId,
    [Parameter()]          [string]$ExistingThumbprint
)

$ErrorActionPreference = 'Stop'

# ----- Default Graph permission matrix (extend via -GraphPermissions) -----
# These are the minimum app-only permissions every SI engine needs. Extra
# permissions (e.g. Mail.Read for SMTP-from-Graph) can be appended via the
# parameter -- they're additive, not replacement.
if (-not $GraphPermissions -or $GraphPermissions.Count -eq 0) {
    $GraphPermissions = @(
        'ThreatHunting.Read.All',                # Defender XDR advanced hunting
        'Device.Read.All',                       # MDE devices, vulnerabilities
        'User.Read.All',                         # Entra users
        'Application.Read.All',                  # SPNs / app regs
        'Group.Read.All',                        # AD groups (for tier-via-membership)
        'Policy.Read.All',                       # Conditional Access + auth policies
        'AuditLog.Read.All',                     # Sign-in logs / audit logs
        'IdentityRiskEvent.Read.All',            # Identity protection risk events
        'IdentityRiskyUser.Read.All',            # Risky users
        'Reports.Read.All',                      # MFA registration + activity reports
        'DirectoryRecommendations.Read.All',     # Defender for Identity + Entra recs
        'SecurityEvents.Read.All',               # Defender alerts
        'CrossTenantInformation.ReadBasic.All', # Multi-tenant SP visibility
        'RoleManagement.Read.Directory'          # v2.2.230 -- /roleManagement/directory/roleDefinitions + roleAssignments + roleEligibilitySchedules (IdentityRoleFetcher in EntraUsers + EntraServicePrincipals discovery). Without this, both sources catch a 403 fetching tenant-wide role definitions and return 0 rows.
    )
}

# ----- Default Microsoft Threat Protection permission matrix (v2.2.231) -----
# Microsoft Threat Protection (resource AppId 8ee8fdad-f234-4243-8f3b-15c294843740)
# is the unified Defender XDR API. AdvancedHunting.Read.All gates the legacy
# advancedhunting/run endpoint that the RiskAnalysis engine probes when Graph's
# /security/runHuntingQuery fails the licensing check. Customers running v2.2.230+
# with only the Graph permission set saw "403 Forbidden" on every XDR-routed
# query in tenants where the unified endpoint isn't available. Extra perms
# can be appended via -ThreatProtectionPermissions.
if (-not $ThreatProtectionPermissions -or $ThreatProtectionPermissions.Count -eq 0) {
    $ThreatProtectionPermissions = @(
        'AdvancedHunting.Read.All'               # Defender XDR Advanced Hunting (MTP API)
    )
}

# ----- Default WindowsDefenderATP permission matrix (v2.2.239) -----
# WindowsDefenderATP (resource AppId fc780465-2017-40d4-a0c5-307022471b92)
# is the legacy MDE API. Machine.Read.All gates the /api/machines endpoint
# (device inventory + secure config status) that the endpoint asset-profiling
# engine reads on tenants where the unified Graph /security/runHuntingQuery
# path isn't available. Without this perm the engine still runs via Graph,
# but tenants on legacy MDE-only licensing get 403 on the device inventory
# fetch. Extra perms can be appended via -WindowsDefenderAtpPermissions.
if (-not $WindowsDefenderAtpPermissions -or $WindowsDefenderAtpPermissions.Count -eq 0) {
    $WindowsDefenderAtpPermissions = @(
        'Machine.Read.All'                       # MDE device inventory + secure config
    )
}

if (-not $RootMgId) { $RootMgId = $TenantId }

# ----- Mode-dependent param validation -----
if ($UseExistingAppId) {
    # Use-existing-SPN mode: caller must supply the AppId of the existing v1
    # cert-based SPN. No DisplayName / CredStorage required (we don't create
    # the app or any new cred). DisplayName gets populated FROM the looked-up
    # app a few steps below.
    if (-not $ExistingAppId) {
        throw "-ExistingAppId is required when -UseExistingAppId is set. Pass the v1 SPN's AppId (typically `$global:HighPriv_Modern_ApplicationID_Azure`)."
    }
    # CredKind defaults to 'Cert' in existing-SPN mode (the v1 cert IS the cred).
    if (-not $PSBoundParameters.ContainsKey('CredKind')) { $CredKind = 'Cert' }
} else {
    # Create-new-SPN mode (the existing wizard / community-flavour path).
    if (-not $DisplayName) {
        throw "-DisplayName is required when not using -UseExistingAppId. Pass a name for the new app registration (e.g. 'sp-securityinsight-<customer>')."
    }
    if (-not $CredStorage) {
        throw "-CredStorage is required when not using -UseExistingAppId. Pick KeyVault | LocalCertStore | Inline."
    }
    # ----- Validate cred-kind / cred-storage combination -----
    switch ($CredKind) {
        'Secret' {
            if ($CredStorage -eq 'LocalCertStore') {
                throw "CredStorage 'LocalCertStore' is only valid with CredKind 'Cert'."
            }
        }
        'Cert' {
            if ($CredStorage -eq 'Inline') {
                throw "CredStorage 'Inline' is only valid with CredKind 'Secret' (a cert thumbprint is fine inline; the private key must live in KV or LocalCertStore)."
            }
        }
        'ManagedIdentity' {
            if (-not $ManagedIdentityClientId) {
                throw "When CredKind = ManagedIdentity, -ManagedIdentityClientId is required (the user-assigned or system-assigned MSI ClientId)."
            }
            # CredStorage is N/A for MSI -- ignored.
        }
    }
    if ($CredKind -ne 'ManagedIdentity' -and $CredStorage -eq 'KeyVault' -and -not $KeyVaultName) {
        throw "When -CredStorage 'KeyVault', -KeyVaultName is required."
    }
}

function _Step([string]$msg) { Write-Host "  [STEP] $msg" -ForegroundColor Cyan }
function _Ok  ([string]$msg) { Write-Host "  [OK]   $msg" -ForegroundColor Green }
function _Info([string]$msg) { Write-Host "  [INFO] $msg" -ForegroundColor Gray }
function _Warn([string]$msg) { Write-Host "  [WARN] $msg" -ForegroundColor Yellow }

Write-Host ""
$bannerLabel = if ($UseExistingAppId) { "USE-EXISTING-SPN appId=$ExistingAppId" } else { $DisplayName }
Write-Host "=== New-SISpn  --  $bannerLabel  ===" -ForegroundColor Cyan
_Info "tenant       : $TenantId"
_Info "subscription : $SubscriptionId"
_Info "root MG      : $RootMgId"
if ($UseExistingAppId) {
    _Info "mode         : USE-EXISTING-SPN (v1 cert-based; no app reg / cred created)"
    if ($ExistingThumbprint) { _Info "cert thumb   : $ExistingThumbprint" }
} else {
    _Info "cred storage : $CredStorage"
}
if ($CredStorage -eq 'KeyVault') { _Info "key vault    : $KeyVaultName / $KvSecretName" }
Write-Host ""

# ----- 1. Connect Microsoft Graph -----
_Step "connect Microsoft Graph"
Import-Module Microsoft.Graph.Authentication -ErrorAction Stop
Import-Module Microsoft.Graph.Applications  -ErrorAction Stop
$mgScopes = @(
    'Application.ReadWrite.All',          # create app + sp + secret
    'AppRoleAssignment.ReadWrite.All',    # grant Microsoft Graph application permissions (admin consent)
    'Directory.ReadWrite.All'             # read SP object IDs for RBAC + member lookup
    # NOTE: DelegatedPermissionGrant.ReadWrite.All intentionally NOT requested.
    # That scope is for delegated (user-impersonation) consent grants. The wizard
    # only does application-only role assignments via AppRoleAssignment.ReadWrite.All.
    # Older docs listed it as required -- it's not, and asking for it triggers
    # AADSTS650053 in some tenants when the Graph SDK truncates the scope on
    # Connect-MgGraph (observed 2026-05-08 against the Graph Command Line Tools
    # public client app).
)
# Graph context MUST be loaded before this cmdlet runs (Start-SetupWizard
# pre-flight requires it; standalone usage = operator runs Connect-MgGraph
# in their shell first). NEVER call Connect-MgGraph here -- in a non-
# interactive listener process the auth dialog is invisible and the cmdlet
# hangs forever, AND device-code auth is blocked by Conditional Access in
# many tenants (security risk). The operator authenticates how their CA
# policy allows in their own shell, then we inherit.
$ctx = Get-MgContext -ErrorAction SilentlyContinue
if (-not $ctx) {
    throw ("No Microsoft Graph context. Run this in the shell that launches the wizard, then re-try:`n  Connect-MgGraph -TenantId {0} -Scopes {1}" -f $TenantId, ($mgScopes -join ','))
}
if ($ctx.TenantId -ne $TenantId) {
    throw ("Graph context tenant mismatch: connected to {0}, wizard wants {1}. Reconnect with 'Connect-MgGraph -TenantId {1} -Scopes {2}'." -f $ctx.TenantId, $TenantId, ($mgScopes -join ','))
}
$missingScopes = @($mgScopes | Where-Object { $ctx.Scopes -notcontains $_ })
if ($missingScopes.Count -gt 0) {
    throw ("Graph context is missing required scopes: {0}. Reconnect with 'Connect-MgGraph -TenantId {1} -Scopes {2}'." -f ($missingScopes -join ','), $TenantId, ($mgScopes -join ','))
}
_Ok ("Graph context: {0} ({1})" -f $ctx.Account, $ctx.AppName)

# ----- 2. Find or create the application -----
if ($UseExistingAppId) {
    _Step ("look up application by AppId {0}" -f $ExistingAppId)
    $app = Get-MgApplication -Filter "appId eq '$ExistingAppId'" -ConsistencyLevel eventual -CountVariable c -ErrorAction Stop
    if ($app -is [array]) { $app = $app[0] }
    if (-not $app) {
        throw ("App registration with AppId '{0}' not found in tenant {1}. Verify the v1 cert-based SPN exists. (Hint: `$global:HighPriv_Modern_ApplicationID_Azure` should resolve to a valid app reg in this tenant.)" -f $ExistingAppId, $TenantId)
    }
    $DisplayName = $app.DisplayName
    _Ok ("re-using existing app reg: {0} (DisplayName='{1}')" -f $app.AppId, $app.DisplayName)
} else {
    _Step "look up application by display name"
    $app = Get-MgApplication -Filter "displayName eq '$DisplayName'" -ConsistencyLevel eventual -CountVariable c -ErrorAction Stop
    if ($app -is [array]) { $app = $app[0] }
    if ($app) {
        _Ok ("re-using existing app reg: {0}" -f $app.AppId)
    } else {
        _Step "create app registration"
        $app = New-MgApplication -DisplayName $DisplayName -SignInAudience 'AzureADMyOrg' -ErrorAction Stop
        _Ok ("created app reg: {0}" -f $app.AppId)
    }
}

# ----- 3. Find or create the service principal -----
_Step "look up service principal"
$sp = Get-MgServicePrincipal -Filter "appId eq '$($app.AppId)'" -ErrorAction SilentlyContinue
if (-not $sp) {
    if ($UseExistingAppId) {
        # In use-existing mode the SP MUST already exist alongside the app reg.
        # Missing SP = the v1 SPN was never fully provisioned. Don't auto-create
        # one -- that masks a deeper config problem.
        throw ("Service Principal for AppId '{0}' not found in tenant {1}. The v1 SPN appears incomplete -- run the v1 Bootstrap-Auth.ps1 (or whatever provisioned the v1 SPN) before re-trying the unattended setup." -f $app.AppId, $TenantId)
    }
    _Step "create service principal"
    $sp = New-MgServicePrincipal -AppId $app.AppId -ErrorAction Stop
    _Ok ("created SP: {0}" -f $sp.Id)
} else {
    _Ok ("re-using existing SP: {0}" -f $sp.Id)
}

# ----- 4. Generate the cred (Secret OR Cert; MSI + UseExistingAppId paths skip this entirely) -----
$pwd       = $null   # secret object
$certInfo  = $null   # @{ Thumbprint; PfxBytes; PfxPassword }
if ($UseExistingAppId) {
    _Info ("UseExistingAppId set -- skipping cred generation; v1 cert in local store (thumbprint {0}) is the credential" -f $ExistingThumbprint)
}
elseif ($CredKind -eq 'Secret') {
    _Step "create new client secret (validity ${SecretValidityYears}y)"
    $secretParams = @{
        PasswordCredential = @{
            DisplayName = ("SI-Wizard-{0:yyyyMMdd-HHmm}" -f (Get-Date))
            EndDateTime = (Get-Date).AddYears($SecretValidityYears)
        }
    }
    $pwd = Add-MgApplicationPassword -ApplicationId $app.Id -BodyParameter $secretParams -ErrorAction Stop
    _Ok ("secret created, expires {0:u}" -f $pwd.EndDateTime)
}
elseif ($CredKind -eq 'Cert') {
    _Step "generate self-signed certificate (validity ${SecretValidityYears}y)"
    $certSubject = "CN=$DisplayName"
    $cert = New-SelfSignedCertificate -Subject $certSubject -CertStoreLocation 'Cert:\CurrentUser\My' `
        -KeySpec Signature -KeyExportPolicy Exportable -KeyLength 2048 `
        -NotAfter (Get-Date).AddYears($SecretValidityYears) -ErrorAction Stop
    _Ok ("cert generated: thumbprint $($cert.Thumbprint), expires $($cert.NotAfter.ToString('u'))")

    _Step "upload cert public key to app registration"
    $certBytes = $cert.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Cert)
    $keyCred = @{
        Type        = 'AsymmetricX509Cert'
        Usage       = 'Verify'
        Key         = $certBytes
        DisplayName = ("SI-Wizard-{0:yyyyMMdd-HHmm}" -f (Get-Date))
        StartDateTime = $cert.NotBefore
        EndDateTime   = $cert.NotAfter
    }
    Update-MgApplication -ApplicationId $app.Id -KeyCredentials @($keyCred) -ErrorAction Stop
    _Ok 'cert public key attached to app registration'

    # Export PFX (pwd-protected, returned to caller for KV upload OR keep in local store)
    $pfxPwd  = [Guid]::NewGuid().Guid
    $pfxBytes = $cert.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Pfx, $pfxPwd)
    $certInfo = @{
        Thumbprint  = $cert.Thumbprint
        NotAfter    = $cert.NotAfter
        PfxBytes    = $pfxBytes
        PfxPassword = $pfxPwd
    }
}
elseif ($CredKind -eq 'ManagedIdentity') {
    _Info "CredKind=ManagedIdentity -- skipping app-reg cred creation; granting perms to the existing MSI"
    $msiSp = Get-MgServicePrincipal -Filter "appId eq '$ManagedIdentityClientId'" -ErrorAction SilentlyContinue
    if (-not $msiSp) {
        throw "Managed Identity with client ID '$ManagedIdentityClientId' not found. Make sure the MSI exists in tenant $TenantId and that you used the CLIENT id, not the principal id."
    }
    # Re-target the rest of the function at the MSI's SP instead of our newly-minted SP.
    $sp = $msiSp
    _Ok ("re-targeting subsequent permissions onto MSI SP {0}" -f $sp.Id)
}

# ----- 5. Add Graph application permissions (per-permission status tracking) -----
# Each permission is one of:
#   granted       - app-role-assignment now in place (operator had Privileged Role Admin)
#   already       - app-role-assignment was already in place (idempotent re-run)
#   pending       - grant attempt failed with Authorization_RequestDenied or similar
#                   (operator lacks PRA / Global Admin); needs another admin to consent
#   not-found     - permission name not on Microsoft Graph's AppRoles (typo / wrong perm)
#   skipped       - SkipAdminConsent switch -- the consent step was deliberately skipped
#                   so the perm is "requested on the app reg" but not yet active
_Step "grant Microsoft Graph application permissions"
$graphAppId  = '00000003-0000-0000-c000-000000000000'   # Microsoft Graph
$graphSp     = Get-MgServicePrincipal -Filter "appId eq '$graphAppId'" -ErrorAction Stop
$permResults = @()                # @{Name; Status; Error}
foreach ($permName in $GraphPermissions) {
    $role = $graphSp.AppRoles | Where-Object { $_.Value -eq $permName -and $_.AllowedMemberTypes -contains 'Application' }
    if (-not $role) {
        _Warn "Graph role not found: $permName -- skipped"
        $permResults += @{ Name = $permName; Status = 'not-found'; Error = 'Permission name not on Microsoft Graph AppRoles' }
        continue
    }
    $existing = Get-MgServicePrincipalAppRoleAssignment -ServicePrincipalId $sp.Id -ErrorAction SilentlyContinue |
        Where-Object { $_.AppRoleId -eq $role.Id -and $_.ResourceId -eq $graphSp.Id }
    if ($existing) {
        $permResults += @{ Name = $permName; Status = 'already'; Error = $null }
        continue
    }
    if ($SkipAdminConsent) {
        $permResults += @{ Name = $permName; Status = 'skipped'; Error = 'SkipAdminConsent set -- a Global Admin must click the consent URL' }
        continue
    }
    try {
        $null = New-MgServicePrincipalAppRoleAssignment -ServicePrincipalId $sp.Id `
            -PrincipalId $sp.Id -ResourceId $graphSp.Id -AppRoleId $role.Id -ErrorAction Stop
        $permResults += @{ Name = $permName; Status = 'granted'; Error = $null }
    } catch {
        # Authorization_RequestDenied = operator lacks PRA / Global Admin. Don't kill
        # the run -- mark the perm pending so the wizard can surface the consent URL
        # and the operator can hand it to a Global Admin (then re-run /api/apply).
        $errMsg = $_.Exception.Message
        _Warn ("could not grant {0}: {1}" -f $permName, $errMsg)
        $permResults += @{ Name = $permName; Status = 'pending'; Error = $errMsg }
    }
}
$grantedCount = ($permResults | Where-Object { $_.Status -in @('granted','already') }).Count
$pendingCount = ($permResults | Where-Object { $_.Status -in @('pending','skipped') }).Count
_Ok ("Graph permissions: {0}/{1} active ({2} pending admin consent)" -f $grantedCount, $GraphPermissions.Count, $pendingCount)

# ----- 5b. Add Microsoft Threat Protection (MTP) application permissions (v2.2.231) -----
# Separate resource SP from Microsoft Graph. AdvancedHunting.Read.All on MTP
# is what gates the legacy advancedhunting/run endpoint -- the RiskAnalysis
# engine probes it as a fallback when Graph's /security/runHuntingQuery isn't
# available. Same per-permission status semantics as the Graph block above.
_Step "grant Microsoft Threat Protection application permissions"
$mtpAppId = '8ee8fdad-f234-4243-8f3b-15c294843740'   # Microsoft Threat Protection
$mtpSp    = Get-MgServicePrincipal -Filter "appId eq '$mtpAppId'" -ErrorAction SilentlyContinue
if (-not $mtpSp) {
    _Warn "Microsoft Threat Protection SP not found in tenant (resourceAppId=$mtpAppId). Skipping MTP perms -- tenant may lack Defender XDR licensing; the engine can still run via Graph hunting."
} else {
    foreach ($permName in $ThreatProtectionPermissions) {
        $role = $mtpSp.AppRoles | Where-Object { $_.Value -eq $permName -and $_.AllowedMemberTypes -contains 'Application' }
        if (-not $role) {
            _Warn "MTP role not found: $permName -- skipped"
            $permResults += @{ Name = $permName; Status = 'not-found'; Error = 'Permission name not on Microsoft Threat Protection AppRoles' }
            continue
        }
        $existing = Get-MgServicePrincipalAppRoleAssignment -ServicePrincipalId $sp.Id -ErrorAction SilentlyContinue |
            Where-Object { $_.AppRoleId -eq $role.Id -and $_.ResourceId -eq $mtpSp.Id }
        if ($existing) {
            $permResults += @{ Name = $permName; Status = 'already'; Error = $null }
            continue
        }
        if ($SkipAdminConsent) {
            $permResults += @{ Name = $permName; Status = 'skipped'; Error = 'SkipAdminConsent set -- a Global Admin must click the consent URL' }
            continue
        }
        try {
            $null = New-MgServicePrincipalAppRoleAssignment -ServicePrincipalId $sp.Id `
                -PrincipalId $sp.Id -ResourceId $mtpSp.Id -AppRoleId $role.Id -ErrorAction Stop
            $permResults += @{ Name = $permName; Status = 'granted'; Error = $null }
        } catch {
            $errMsg = $_.Exception.Message
            _Warn ("could not grant {0}: {1}" -f $permName, $errMsg)
            $permResults += @{ Name = $permName; Status = 'pending'; Error = $errMsg }
        }
    }
    $mtpResults = $permResults | Where-Object { $_.Name -in $ThreatProtectionPermissions }
    $mtpGranted = ($mtpResults | Where-Object { $_.Status -in @('granted','already') }).Count
    $mtpPending = ($mtpResults | Where-Object { $_.Status -in @('pending','skipped') }).Count
    _Ok ("MTP permissions: {0}/{1} active ({2} pending admin consent)" -f $mtpGranted, $ThreatProtectionPermissions.Count, $mtpPending)
}

# ----- 5c. Add WindowsDefenderATP application permissions (v2.2.239) -----
# Separate resource SP from Microsoft Graph + MTP. Machine.Read.All on
# WindowsDefenderATP unlocks the legacy MDE /api/machines inventory endpoint
# the endpoint asset-profiling engine reads on tenants where the unified
# Graph /security/runHuntingQuery path isn't available. Soft-fails when the
# WindowsDefenderATP SP isn't present (no MDE licensing) so the wizard run
# completes regardless.
_Step "grant WindowsDefenderATP application permissions"
$mdeAppId = 'fc780465-2017-40d4-a0c5-307022471b92'   # WindowsDefenderATP
$mdeSp    = Get-MgServicePrincipal -Filter "appId eq '$mdeAppId'" -ErrorAction SilentlyContinue
if (-not $mdeSp) {
    _Warn "WindowsDefenderATP SP not found in tenant (resourceAppId=$mdeAppId). Skipping MDE perms -- tenant may lack MDE licensing; the engine can still run via Graph hunting."
} else {
    foreach ($permName in $WindowsDefenderAtpPermissions) {
        $role = $mdeSp.AppRoles | Where-Object { $_.Value -eq $permName -and $_.AllowedMemberTypes -contains 'Application' }
        if (-not $role) {
            _Warn "MDE role not found: $permName -- skipped"
            $permResults += @{ Name = $permName; Status = 'not-found'; Error = 'Permission name not on WindowsDefenderATP AppRoles' }
            continue
        }
        $existing = Get-MgServicePrincipalAppRoleAssignment -ServicePrincipalId $sp.Id -ErrorAction SilentlyContinue |
            Where-Object { $_.AppRoleId -eq $role.Id -and $_.ResourceId -eq $mdeSp.Id }
        if ($existing) {
            $permResults += @{ Name = $permName; Status = 'already'; Error = $null }
            continue
        }
        if ($SkipAdminConsent) {
            $permResults += @{ Name = $permName; Status = 'skipped'; Error = 'SkipAdminConsent set -- a Global Admin must click the consent URL' }
            continue
        }
        try {
            $null = New-MgServicePrincipalAppRoleAssignment -ServicePrincipalId $sp.Id `
                -PrincipalId $sp.Id -ResourceId $mdeSp.Id -AppRoleId $role.Id -ErrorAction Stop
            $permResults += @{ Name = $permName; Status = 'granted'; Error = $null }
        } catch {
            $errMsg = $_.Exception.Message
            _Warn ("could not grant {0}: {1}" -f $permName, $errMsg)
            $permResults += @{ Name = $permName; Status = 'pending'; Error = $errMsg }
        }
    }
    $mdeResults = $permResults | Where-Object { $_.Name -in $WindowsDefenderAtpPermissions }
    $mdeGranted = ($mdeResults | Where-Object { $_.Status -in @('granted','already') }).Count
    $mdePending = ($mdeResults | Where-Object { $_.Status -in @('pending','skipped') }).Count
    _Ok ("MDE permissions: {0}/{1} active ({2} pending admin consent)" -f $mdeGranted, $WindowsDefenderAtpPermissions.Count, $mdePending)
}

# Compute an admin-consent URL the wizard UI can surface to the operator. A
# Global Admin (or anyone with Privileged Role Administrator on the app) clicks
# this URL once and consents to all the requested permissions in a single
# Entra portal flow -- works regardless of whether the wizard's operator had
# the rights to do it themselves.
$consentUrl = "https://login.microsoftonline.com/$TenantId/adminconsent?client_id=$($app.AppId)"
$consentStatus = if ($pendingCount -eq 0) { 'granted' }
                 elseif ($grantedCount -eq 0) { 'pending' }
                 else { 'partial' }
_Info "consent status: $consentStatus"
if ($consentStatus -ne 'granted') {
    _Info "admin consent URL (hand to a Global Admin, then re-run /api/apply):"
    _Info "  $consentUrl"
}

# ----- 6. Azure RBAC -----
# Az context MUST be loaded before this cmdlet runs (Start-SetupWizard's
# pre-flight requires both Az + Graph contexts; running standalone, the
# operator does Connect-AzAccount in their shell before invoking us). NEVER
# call Connect-AzAccount here -- in a non-interactive listener process the
# auth dialog is invisible and the cmdlet hangs forever (root cause of the
# v2.2.105-v2.2.112 listener stall in Phase 1).
_Step "verify Az PowerShell context"
Import-Module Az.Accounts -ErrorAction Stop
Import-Module Az.Resources -ErrorAction Stop
$azCtx = Get-AzContext -ErrorAction SilentlyContinue
if (-not $azCtx) {
    throw "No Az PowerShell context. Run 'Connect-AzAccount -Tenant $TenantId' in the shell that launches the wizard, then re-try."
}
if ($azCtx.Tenant.Id -ne $TenantId) {
    throw ("Az context tenant mismatch: connected to {0}, wizard wants {1}. Reconnect with 'Connect-AzAccount -Tenant {1}'." -f $azCtx.Tenant.Id, $TenantId)
}
if ($azCtx.Subscription.Id -ne $SubscriptionId) {
    Set-AzContext -SubscriptionId $SubscriptionId -ErrorAction Stop | Out-Null
    $azCtx = Get-AzContext
}
_Ok ("Az context: {0} (sub: {1} / {2})" -f $azCtx.Account.Id, $azCtx.Subscription.Name, $azCtx.Subscription.Id)

$rbacScopes  = @()
$rbacResults = @()                # @{Name; Scope; Status; Error}
$rootMgScope = "/providers/Microsoft.Management/managementGroups/$RootMgId"
$readerRoleId       = 'acdd72a7-3385-48ef-bd42-f606fba81ae7'   # Reader
$tagContributorId   = '4a9ae827-6dc8-4573-8ac7-8239d42aa03f'   # Tag Contributor

# Build the role list for tenant-root MG. Reader is always included (drives
# subscription discovery + cross-sub LA queries). Tag Contributor is OPT-IN
# only when -IncludeTagContributor is set -- it's needed exclusively by the
# asset-exclusion-tagging engine, which most customers don't run. Granting
# Tag Contributor at tenant-root MG by default is too broad: it lets the SPN
# write tags to every resource in every subscription in the tenant.
$tenantRolePairs = @(@{Name='Reader'; Id=$readerRoleId})
if ($IncludeTagContributor) {
    $tenantRolePairs += @{Name='Tag Contributor'; Id=$tagContributorId}
}

if ($SkipTenantRbac) {
    $rolesSkipped = ($tenantRolePairs | ForEach-Object { $_.Name }) -join ' + '
    _Info ("SkipTenantRbac set -- skipping {0} at tenant-root MG" -f $rolesSkipped)
    foreach ($pair in $tenantRolePairs) {
        $rbacResults += @{ Name = $pair.Name; Scope = $rootMgScope; Status = 'skipped'; Error = 'SkipTenantRbac set' }
    }
} else {
    foreach ($pair in $tenantRolePairs) {
        $existing = Get-AzRoleAssignment -ObjectId $sp.Id -Scope $rootMgScope -RoleDefinitionId $pair.Id -ErrorAction SilentlyContinue
        if ($existing) {
            _Info ("RBAC {0} already in place at root MG" -f $pair.Name)
            $rbacResults += @{ Name = $pair.Name; Scope = $rootMgScope; Status = 'already'; Error = $null }
            continue
        }
        try {
            $null = New-AzRoleAssignment -ObjectId $sp.Id -RoleDefinitionId $pair.Id -Scope $rootMgScope -ErrorAction Stop
            _Ok ("RBAC {0} granted at root MG" -f $pair.Name)
            $rbacScopes += "$rootMgScope|$($pair.Name)"
            $rbacResults += @{ Name = $pair.Name; Scope = $rootMgScope; Status = 'granted'; Error = $null }
        } catch {
            $errMsg = $_.Exception.Message
            _Warn ("RBAC {0} grant failed: {1}" -f $pair.Name, $errMsg)
            $rbacResults += @{ Name = $pair.Name; Scope = $rootMgScope; Status = 'pending'; Error = $errMsg }
        }
    }
}

# ----- 7. Cred storage -----
$credValue        = $null
$kvOut            = $null
$kvSecretOut      = $null
$kvCertOut        = $null
$certThumbprintOut= $null
$expiresOut       = $null

if ($UseExistingAppId) {
    # Existing v1 cert in local store; we don't generate / move / store anything.
    # CertThumbprint surfaces in the result so the caller can confirm parity
    # with what they passed in.
    $certThumbprintOut = $ExistingThumbprint
    _Info "cred storage = ExistingCert -- v1 cert in local store; nothing written"
}
elseif ($CredKind -eq 'Secret') {
    if ($CredStorage -eq 'KeyVault') {
        _Step "store secret in Key Vault"
        Import-Module Az.KeyVault -ErrorAction Stop
        $kv = Get-AzKeyVault -VaultName $KeyVaultName -ErrorAction SilentlyContinue
        if (-not $kv) { throw "Key Vault '$KeyVaultName' not found in subscription $SubscriptionId" }
        $secureSecret = ConvertTo-SecureString -String $pwd.SecretText -AsPlainText -Force
        $null = Set-AzKeyVaultSecret -VaultName $KeyVaultName -Name $KvSecretName -SecretValue $secureSecret -Expires $pwd.EndDateTime -ErrorAction Stop
        _Ok ("secret stored at https://{0}.vault.azure.net/secrets/{1}" -f $KeyVaultName, $KvSecretName)
        $kvOut = $KeyVaultName; $kvSecretOut = $KvSecretName
    } else {
        _Info 'cred storage = Inline -- secret returned in result object (DO NOT log)'
        $credValue = $pwd.SecretText
    }
    $expiresOut = $pwd.EndDateTime.ToUniversalTime()
}
elseif ($CredKind -eq 'Cert') {
    $certThumbprintOut = $certInfo.Thumbprint
    $expiresOut        = $certInfo.NotAfter.ToUniversalTime()
    if ($CredStorage -eq 'KeyVault') {
        _Step "store cert .pfx in Key Vault"
        Import-Module Az.KeyVault -ErrorAction Stop
        $kv = Get-AzKeyVault -VaultName $KeyVaultName -ErrorAction SilentlyContinue
        if (-not $kv) { throw "Key Vault '$KeyVaultName' not found in subscription $SubscriptionId" }
        $tmpPfx = Join-Path ([IO.Path]::GetTempPath()) ("$DisplayName-{0:yyyyMMddHHmmss}.pfx" -f (Get-Date))
        try {
            [IO.File]::WriteAllBytes($tmpPfx, $certInfo.PfxBytes)
            $securePfxPwd = ConvertTo-SecureString -String $certInfo.PfxPassword -AsPlainText -Force
            $null = Import-AzKeyVaultCertificate -VaultName $KeyVaultName -Name $KvCertName -FilePath $tmpPfx -Password $securePfxPwd -ErrorAction Stop
            _Ok ("cert stored at https://{0}.vault.azure.net/certificates/{1}" -f $KeyVaultName, $KvCertName)
            $kvOut     = $KeyVaultName
            $kvCertOut = $KvCertName
        } finally {
            if (Test-Path -LiteralPath $tmpPfx) { Remove-Item -LiteralPath $tmpPfx -Force -ErrorAction SilentlyContinue }
        }
    } elseif ($CredStorage -eq 'LocalCertStore') {
        _Info ("cert kept in CurrentUser\My (thumbprint $($certInfo.Thumbprint)) -- private key stays on this machine only")
        # Already in CurrentUser\My from New-SelfSignedCertificate. Nothing else to do.
    }
}
elseif ($CredKind -eq 'ManagedIdentity') {
    _Info "MSI mode: app-reg cred not generated. The launcher must run on the host that owns this MSI."
    $expiresOut = $null
}

Write-Host ""
[pscustomobject]@{
    AppId             = $app.AppId
    ObjectId          = $sp.Id
    TenantId          = $TenantId
    DisplayName       = $DisplayName
    CredKind          = $CredKind
    CredValue         = $credValue          # Secret + Inline only
    CertThumbprint    = $certThumbprintOut  # Cert path only
    KvName            = $kvOut
    KvSecretName      = $kvSecretOut        # Secret-in-KV
    KvCertName        = $kvCertOut          # Cert-in-KV
    ManagedIdentityId = if ($CredKind -eq 'ManagedIdentity') { $ManagedIdentityClientId } else { $null }
    ExpiresUtc        = $expiresOut
    GraphPermissions  = $GraphPermissions
    GraphPermissionResults = $permResults    # @[{Name; Status; Error}, ...]
    PendingPermissions     = ($permResults | Where-Object { $_.Status -in @('pending','skipped') } | ForEach-Object { $_.Name })
    ConsentStatus          = $consentStatus  # granted | partial | pending
    ConsentUrl             = $consentUrl     # hand to a Global Admin
    AzureRbacScopes        = $rbacScopes
    AzureRbacResults       = $rbacResults    # @[{Name; Scope; Status; Error}, ...]
}
