<#
.SYNOPSIS
    Renders config\SecurityInsight.custom.ps1 from the Setup Wizard's collected state.

.DESCRIPTION
    Combines outputs from New-SISpn + Initialize-SIInfra (the SPN block + workspace /
    DCE / DCR / storage block) with optional sections the wizard's pages collected
    (SMTP, Azure OpenAI, Shodan, CMDB, per-engine JSON sink), and writes a complete
    SecurityInsight.custom.ps1 to disk.

    Idempotent. If the target file exists, backs it up to *.bak.<timestamp> before
    overwriting -- never silently destroys an operator's customizations.

    Storage: when -StorageMode 'RBAC' (default for v2.2.105+), $global:SI_StorageKey
    is OMITTED from the file. Engine v2.2.79+ auto-detects OAuth-on-storage when no
    key is set.

.PARAMETER OutputPath
    Where to write the file. Default: <repo>\config\SecurityInsight.custom.ps1.

.PARAMETER Spn
    Output object from New-SISpn. Required.

.PARAMETER Infra
    Output object from Initialize-SIInfra. Required.

.PARAMETER Smtp
    Optional hashtable. Keys: Server, Port, UseSsl, User, Password, From, MailTo[],
    DetailedTo[], SummaryTo[]. Omit to skip the SMTP section entirely.

.PARAMETER OpenAi
    Optional hashtable. Keys: Endpoint, Deployment, ApiKey, ApiVersion, MaxTokens, MaxSpendUsd.

.PARAMETER Shodan
    Optional hashtable. Keys: ApiKey, ExtraTargets[].

.PARAMETER Cmdb
    Optional hashtable. Keys: Enabled, RefreshHours, CsvPath.

.PARAMETER EnableJsonSink
    Add 'JSON' to every SI_Sinks_<Engine> array. Default $false (LA + Excel only).

.PARAMETER DefenderWorkspaceResourceId
    Optional. ResourceId of a separate Sentinel/Defender workspace where Entra
    diagnostic logs land (read-only).

.OUTPUTS
    pscustomobject @{ Path; Bytes; Sections; Backup }

.NOTES
    Status: v2.2.105 -- ships with New-SISpn + Initialize-SIInfra + /api/apply.
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter()]          [string]$OutputPath,
    [Parameter(Mandatory)] [object]$Spn,
    [Parameter(Mandatory)] [object]$Infra,
    [Parameter()]          [hashtable]$Smtp,
    [Parameter()]          [hashtable]$OpenAi,
    [Parameter()]          [hashtable]$Shodan,
    [Parameter()]          [hashtable]$Cmdb,
    [Parameter()]          [switch]$EnableJsonSink,
    [Parameter()]          [string]$DefenderWorkspaceResourceId
)

$ErrorActionPreference = 'Stop'

if (-not $OutputPath) {
    # Resolve <SI repo root>\config\SecurityInsight.custom.ps1 by walking up from
    # this script's location.
    $cur = $PSScriptRoot
    while ($cur -and -not (Test-Path -LiteralPath (Join-Path $cur 'VERSION'))) {
        $parent = Split-Path -Parent $cur
        if (-not $parent -or $parent -eq $cur) { $cur = $null; break }
        $cur = $parent
    }
    if (-not $cur) { throw 'Could not auto-resolve SI repo root. Pass -OutputPath explicitly.' }
    $OutputPath = Join-Path $cur 'config\SecurityInsight.custom.ps1'
}

function _Step([string]$msg) { Write-Host "  [STEP] $msg" -ForegroundColor Cyan }
function _Ok  ([string]$msg) { Write-Host "  [OK]   $msg" -ForegroundColor Green }
function _Info([string]$msg) { Write-Host "  [INFO] $msg" -ForegroundColor Gray }

Write-Host ""
Write-Host "=== Write-SICustomConfig ===" -ForegroundColor Cyan
_Info "output : $OutputPath"
Write-Host ""

# ---------- Build sections ----------
$sb = New-Object System.Text.StringBuilder
$sectionsWritten = @()
$null = $sb.AppendLine("#Requires -Version 5.1")
$null = $sb.AppendLine("<#")
$null = $sb.AppendLine("    SecurityInsight customer config -- generated by Setup Wizard.")
$null = $sb.AppendLine("    Generated UTC: $((Get-Date).ToUniversalTime().ToString('u'))")
$null = $sb.AppendLine("    DO NOT commit this file. config\ is gitignored on purpose.")
$null = $sb.AppendLine("#>")
$null = $sb.AppendLine()

# ---- 1. SPN ----
$null = $sb.AppendLine("# ============================================================================")
$null = $sb.AppendLine("# 1. SPN  --  identity SI uses for Graph + Az + LA Ingest")
$null = $sb.AppendLine("# ============================================================================")
$null = $sb.AppendLine("`$global:SI_SPN_AppId    = '$($Spn.AppId)'")
$null = $sb.AppendLine("`$global:SI_SPN_TenantId = '$($Spn.TenantId)'")
$null = $sb.AppendLine("`$global:SI_SPN_ObjectId = '$($Spn.ObjectId)'")
switch ($Spn.CredKind) {
    'Secret' {
        if ($Spn.CredValue) {
            $null = $sb.AppendLine("`$global:SI_SPN_Secret   = '$($Spn.CredValue)'")
        }
        if ($Spn.KvName) {
            $null = $sb.AppendLine("`$global:SI_KeyVaultName       = '$($Spn.KvName)'")
            $null = $sb.AppendLine("`$global:SI_SPN_KvSecretName   = '$($Spn.KvSecretName)'")
        }
    }
    'Cert' {
        $null = $sb.AppendLine("`$global:SI_SPN_CertThumbprint = '$($Spn.CertThumbprint)'")
        if ($Spn.KvName) {
            $null = $sb.AppendLine("`$global:SI_KeyVaultName     = '$($Spn.KvName)'")
            $null = $sb.AppendLine("`$global:SI_SPN_KvCertName   = '$($Spn.KvCertName)'")
        }
    }
    'ManagedIdentity' {
        $null = $sb.AppendLine("`$global:SI_SPN_UseManagedIdentity = `$true")
        $null = $sb.AppendLine("`$global:SI_SPN_ManagedIdentityClientId = '$($Spn.ManagedIdentityId)'")
    }
}
$null = $sb.AppendLine()
$sectionsWritten += 'SPN'

# ---- 2. Infrastructure (workspace + DCE + DCR) ----
$null = $sb.AppendLine("# ============================================================================")
$null = $sb.AppendLine("# 2. INFRASTRUCTURE  --  workspace / DCE / DCRs (engine creates if missing)")
$null = $sb.AppendLine("# ============================================================================")
$null = $sb.AppendLine("`$global:SI_PrestageInfra              = `$true")
$null = $sb.AppendLine("`$global:SI_Location                   = '$($Infra.Location)'")
$null = $sb.AppendLine("`$global:SI_AzSubscriptionId           = '$($Infra.SubscriptionId)'")
$null = $sb.AppendLine()
$null = $sb.AppendLine("`$global:SI_WorkspaceName              = '$($Infra.WorkspaceName)'")
$null = $sb.AppendLine("`$global:SI_WorkspaceResourceGroup     = '$($Infra.ResourceGroupName)'")
$null = $sb.AppendLine("`$global:SI_WorkspaceResourceId        = '$($Infra.WorkspaceResourceId)'")
if ($DefenderWorkspaceResourceId) {
    $null = $sb.AppendLine("`$global:SI_DefenderWorkspaceResourceId = '$DefenderWorkspaceResourceId'")
}
$null = $sb.AppendLine()
$null = $sb.AppendLine("`$global:SI_DceName                    = '$($Infra.DceName)'")
$null = $sb.AppendLine("`$global:SI_DceIngestionUri            = '$($Infra.DceIngestionUri)'")
$null = $sb.AppendLine("`$global:SI_DceResourceGroup           = '$($Infra.ResourceGroupName)'")
$null = $sb.AppendLine("`$global:SI_DcrResourceGroup           = '$($Infra.DcrResourceGroupName)'")
$null = $sb.AppendLine()
$null = $sb.AppendLine("`$global:SI_TableNamePattern           = 'SI_{0}_Profile'")
$null = $sb.AppendLine("`$global:SI_DcrNamePattern             = 'dcr-si-{0}'")
$null = $sb.AppendLine()
$null = $sb.AppendLine("# Per-engine DCR overrides (default names; edit if you collide with existing tables in the workspace)")
$null = $sb.AppendLine("`$global:SI_Shodan_DcrName                = 'dcr-si-publicip'")
$null = $sb.AppendLine("`$global:SI_RiskAnalysis_DcrName_Detailed = 'dcr-si-risk-analysis-detailed'")
$null = $sb.AppendLine("`$global:SI_RiskAnalysis_DcrName_Summary  = 'dcr-si-risk-analysis-summary'")
$null = $sb.AppendLine("`$global:SI_RunHealth_DcrName             = 'dcr-si-run-health'")
$null = $sb.AppendLine("`$global:SI_SchemaCatalogDcr              = 'dcr-si-schema-catalog'")
$null = $sb.AppendLine("`$global:SI_AssetTagActivityDcr           = 'dcr-si-assettag-activity'")
$null = $sb.AppendLine()
$sectionsWritten += 'Infrastructure'

# ---- 3. Storage (RBAC-only, no key) ----
$null = $sb.AppendLine("# ============================================================================")
$null = $sb.AppendLine("# 3. STORAGE  --  RBAC-only mode (no shared key written here)")
$null = $sb.AppendLine("# ============================================================================")
$null = $sb.AppendLine("`$global:SI_StorageAccount             = '$($Infra.StorageAccountName)'")
$null = $sb.AppendLine("`$global:SI_StorageResourceGroup       = '$($Infra.StorageResourceGroupName)'")
$null = $sb.AppendLine("# (NO `$global:SI_StorageKey -- engine uses OAuth via SPN/MSI when the key is absent)")
$null = $sb.AppendLine("# Force OAuth-only auth: SPN has Storage Blob/Table/Queue Data Contributor but")
$null = $sb.AppendLine("# NOT 'listKeys' permission. Without this flag the engine probes Get-AzStorageAccountKey")
$null = $sb.AppendLine("# first and warns 'Forbidden' before falling back; setting this skips the probe.")
$null = $sb.AppendLine("`$global:SI_UseStorageOAuth            = `$true")
$null = $sb.AppendLine()
$sectionsWritten += 'Storage'

# ---- 4. Output sinks ----
$sinks = if ($EnableJsonSink) { "@('LA','Excel','JSON')" } else { "@('LA','Excel')" }
$null = $sb.AppendLine("# ============================================================================")
$null = $sb.AppendLine("# 4. OUTPUT SINKS  --  per-engine output destinations")
$null = $sb.AppendLine("# ============================================================================")
$null = $sb.AppendLine("`$global:SI_Sinks_Endpoint = $sinks")
$null = $sb.AppendLine("`$global:SI_Sinks_Identity = $sinks")
$null = $sb.AppendLine("`$global:SI_Sinks_Azure    = $sinks")
$null = $sb.AppendLine("`$global:SI_Sinks_PublicIp = $sinks")
$null = $sb.AppendLine("`$global:SendToLogAnalytics = `$true")
$null = $sb.AppendLine()
$sectionsWritten += 'Sinks'

# ---- 5. SMTP (optional) ----
# Only emit the SMTP block when there's actually a server to send through. A
# hashtable with all-null fields can leak through when the wizard state still
# carries a stale smtp object the operator selected then turned off.
if ($Smtp -and $Smtp.Server) {
    $null = $sb.AppendLine("# ============================================================================")
    $null = $sb.AppendLine("# 5. SMTP  --  email dispatch")
    $null = $sb.AppendLine("# ============================================================================")
    $null = $sb.AppendLine("`$global:SendMail        = `$true")
    if ($Smtp.MailTo)     { $null = $sb.AppendLine("`$global:MailTo          = @($(($Smtp.MailTo     | ForEach-Object { "'$_'" }) -join ','))") }
    if ($Smtp.Server)     { $null = $sb.AppendLine("`$global:SmtpServer      = '$($Smtp.Server)'") }
    if ($Smtp.Port)       { $null = $sb.AppendLine("`$global:SmtpPort        = $([int]$Smtp.Port)") }
    if ($Smtp.User)       { $null = $sb.AppendLine("`$global:SMTPUser        = '$($Smtp.User)'") }
    if ($Smtp.Password)   { $null = $sb.AppendLine("`$global:SMTPPassword    = '$($Smtp.Password)'") }
    if ($Smtp.From)       { $null = $sb.AppendLine("`$global:SMTPFrom        = '$($Smtp.From)'") }
    $useSsl = if ($null -ne $Smtp.UseSsl) { [bool]$Smtp.UseSsl } else { $true }
    $null = $sb.AppendLine("`$global:SMTP_UseSSL     = `$" + ($useSsl.ToString().ToLower()))
    if ($Smtp.DetailedTo) {
        $list = ($Smtp.DetailedTo | ForEach-Object { "'$_'" }) -join ','
        $null = $sb.AppendLine("`$global:RiskAnalysis_Detailed_SendMail = `$true")
        $null = $sb.AppendLine("`$global:RiskAnalysis_Detailed_To       = @($list)")
        $null = $sb.AppendLine("`$global:Mail_SecurityInsight_Detailed_SendMail = `$true")
        $null = $sb.AppendLine("`$global:Mail_SecurityInsight_Detailed_To       = @($list)")
    }
    if ($Smtp.SummaryTo) {
        $list = ($Smtp.SummaryTo | ForEach-Object { "'$_'" }) -join ','
        $null = $sb.AppendLine("`$global:RiskAnalysis_Summary_SendMail  = `$true")
        $null = $sb.AppendLine("`$global:RiskAnalysis_Summary_To        = @($list)")
        $null = $sb.AppendLine("`$global:Mail_SecurityInsight_Summary_SendMail = `$true")
        $null = $sb.AppendLine("`$global:Mail_SecurityInsight_Summary_To       = @($list)")
    }
    $null = $sb.AppendLine()
    $sectionsWritten += 'SMTP'
}

# ---- 6. Engine tuning (sensible defaults) ----
$null = $sb.AppendLine("# ============================================================================")
$null = $sb.AppendLine("# 6. ENGINE TUNING  --  sensible defaults; override per tenant if needed")
$null = $sb.AppendLine("# ============================================================================")
foreach ($e in 'Endpoint','Identity','Azure','PublicIp') {
    $null = $sb.AppendLine("`$global:SI_AssetLimit_$e   = 0")
    $null = $sb.AppendLine("`$global:SI_ForceFullRun_$e = `$true")
}
$null = $sb.AppendLine("`$global:SI_ActiveStaleDays = 30")
$null = $sb.AppendLine()
$sectionsWritten += 'EngineTuning'

# ---- 7. RA defaults ----
$null = $sb.AppendLine("# ============================================================================")
$null = $sb.AppendLine("# 7. RISK ANALYSIS  --  bucket / overwrite defaults")
$null = $sb.AppendLine("# ============================================================================")
$null = $sb.AppendLine("`$global:RiskAnalysis_Summary_Override  = `$true")
$null = $sb.AppendLine("`$global:RiskAnalysis_Detailed_Override = `$false")
$null = $sb.AppendLine("`$global:AutoBucketCount = `$true")
$null = $sb.AppendLine("`$global:AutoBucketMax   = 1024")
$null = $sb.AppendLine("`$global:AutoBucketCache = `$true")
$null = $sb.AppendLine("`$global:OverwriteXlsx   = `$true")
$null = $sb.AppendLine()
$sectionsWritten += 'RA'

# ---- 8. Azure OpenAI (optional) ----
# Endpoint is required for any AI call; without it the section is meaningless.
if ($OpenAi -and $OpenAi.Endpoint) {
    $null = $sb.AppendLine("# ============================================================================")
    $null = $sb.AppendLine("# 8. AZURE OPENAI  --  Build_Tier + RA -BuildSummaryByAI")
    $null = $sb.AppendLine("# ============================================================================")
    if ($OpenAi.Endpoint)   { $null = $sb.AppendLine("`$global:OpenAI_endpoint            = '$($OpenAi.Endpoint)'") }
    if ($OpenAi.Deployment) { $null = $sb.AppendLine("`$global:OpenAI_deployment          = '$($OpenAi.Deployment)'") }
    if ($OpenAi.ApiKey)     { $null = $sb.AppendLine("`$global:OpenAI_apiKey              = '$($OpenAi.ApiKey)'") }
    if ($OpenAi.ApiVersion) { $null = $sb.AppendLine("`$global:OpenAI_apiVersion          = '$($OpenAi.ApiVersion)'") } else { $null = $sb.AppendLine("`$global:OpenAI_apiVersion          = '2025-01-01-preview'") }
    if ($OpenAi.MaxTokens)  { $null = $sb.AppendLine("`$global:OpenAI_MaxTokensPerRequest = $([int]$OpenAi.MaxTokens)") } else { $null = $sb.AppendLine("`$global:OpenAI_MaxTokensPerRequest = 16384") }
    if ($OpenAi.MaxSpendUsd){ $null = $sb.AppendLine("`$global:MaxAiSpendPerRun           = $([int]$OpenAi.MaxSpendUsd)") } else { $null = $sb.AppendLine("`$global:MaxAiSpendPerRun           = 4") }
    $null = $sb.AppendLine("`$global:BuildSummaryByAI = `$true")
    $null = $sb.AppendLine()
    $sectionsWritten += 'OpenAI'
}

# ---- 9. Shodan (optional) ----
if ($Shodan -and $Shodan.ApiKey) {
    $null = $sb.AppendLine("# ============================================================================")
    $null = $sb.AppendLine("# 9. SHODAN  --  PublicIP scanner")
    $null = $sb.AppendLine("# ============================================================================")
    $null = $sb.AppendLine("`$global:SI_Shodan_ApiKey = '$($Shodan.ApiKey)'")
    if ($Shodan.ExtraTargets) {
        $list = ($Shodan.ExtraTargets | ForEach-Object { "'$_'" }) -join ','
        $null = $sb.AppendLine("`$global:SI_PublicIP_ExtraTargets = @($list)")
    }
    $null = $sb.AppendLine()
    $sectionsWritten += 'Shodan'
}

# ---- 10. CMDB (optional) ----
if ($Cmdb -and $Cmdb.Enabled) {
    $null = $sb.AppendLine("# ============================================================================")
    $null = $sb.AppendLine("# 10. CMDB PROVIDER  --  ServiceNow CMDB CSV")
    $null = $sb.AppendLine("# ============================================================================")
    $null = $sb.AppendLine("`$global:SI_EnableCmdbProvider       = `$true")
    $hours = if ($Cmdb.RefreshHours) { [int]$Cmdb.RefreshHours } else { 24 }
    $null = $sb.AppendLine("`$global:SI_CmdbRefreshIntervalHours = $hours")
    if ($Cmdb.CsvPath) { $null = $sb.AppendLine("`$global:SI_CmdbCsvPath              = '$($Cmdb.CsvPath)'") }
    $null = $sb.AppendLine()
    $sectionsWritten += 'CMDB'
}

# ---- 11. Provenance footer ----
$null = $sb.AppendLine("# ============================================================================")
$null = $sb.AppendLine("# Generated by Setup Wizard v2.2.105+ -- regenerate via .\setup\ConfigWizard\Start-SetupWizard.ps1")
$null = $sb.AppendLine("# ============================================================================")

$content = $sb.ToString()

# ---------- Backup + write ----------
$backup = $null
if (Test-Path -LiteralPath $OutputPath) {
    $backup = "$OutputPath.bak.{0:yyyyMMdd-HHmmss}" -f (Get-Date)
    _Step "backup existing custom file -> $backup"
    Copy-Item -LiteralPath $OutputPath -Destination $backup -Force
    _Ok 'backup created'
}

# Make sure parent exists
$parentDir = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $parentDir)) {
    New-Item -ItemType Directory -Path $parentDir -Force | Out-Null
}

_Step "write $OutputPath"
[IO.File]::WriteAllText($OutputPath, $content, [Text.UTF8Encoding]::new($false))
$bytes = (Get-Item -LiteralPath $OutputPath).Length
_Ok "wrote $bytes bytes ($(($sectionsWritten -join ', ')))"

[pscustomobject]@{
    Path     = $OutputPath
    Bytes    = $bytes
    Sections = $sectionsWritten
    Backup   = $backup
}
